import DashboardLayout from "@/components/layout/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, MessageSquare, Sparkles, Wand2, Zap, FileText } from "lucide-react";
import { RebookedAIChat } from "@/components/chat/RebookedAIChat";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { HelpTooltip } from "@/components/ui/HelpTooltip";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

const AI_CAPABILITIES = [
  {
    icon: MessageSquare,
    title: "Message Generator",
    tooltip: "Describe a scenario and the AI will write a ready-to-send SMS for you.",
    description: "Generate personalized SMS messages for any scenario — appointment reminders, no-show recovery, rebooking offers, and more.",
    color: "text-primary",
  },
  {
    icon: Wand2,
    title: "Tone Rewriter",
    tooltip: "Uses AI to reword your message templates for better engagement while keeping your meaning intact.",
    description: "Rewrite any message in the perfect tone — friendly, professional, casual, urgent, or empathetic.",
    color: "text-accent-foreground",
  },
  {
    icon: Sparkles,
    title: "Smart Suggestions",
    tooltip: "AI analyses your automations and suggests changes that could improve open and response rates.",
    description: "Get AI-powered suggestions to improve your automations and boost recovery rates.",
    color: "text-warning",
  },
  {
    icon: Zap,
    title: "Automation Templates",
    tooltip: "Pre-built automation workflows generated by AI and tailored to your specific business type.",
    description: "AI-generated automation templates tailored to your industry and business type.",
    color: "text-info",
  },
  {
    icon: FileText,
    title: "Message Variations",
    tooltip: "Generate multiple versions of a single message to A/B test which drives the most bookings.",
    description: "Generate multiple variations of any message to A/B test and find what works best.",
    color: "text-primary",
  },
  {
    icon: Bot,
    title: "RebookedAI Assistant",
    tooltip: "A conversational AI that knows your account — ask it anything about setup, best practices, or your data.",
    description: "Ask questions about your account, get help with setup, or learn best practices.",
    color: "text-success",
  },
];

export default function AiTools() {
  const [showChat, setShowChat] = useState(false);

  return (
    <DashboardLayout>
      <div className="space-y-6 p-6">
        <div className="flex items-center justify-between">
          <div>
            <HelpTooltip content="RebookedAI is a suite of AI tools built into the platform. Use it to generate SMS messages, rewrite templates, get optimisation suggestions, and chat with an assistant that knows your account." variant="tip">
              <h1 className="text-2xl font-bold tracking-tight">RebookedAI Tools</h1>
            </HelpTooltip>
            <p className="text-muted-foreground">
              AI-powered tools to help you recover more revenue and save time.
            </p>
          </div>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button onClick={() => setShowChat(!showChat)} variant={showChat ? "secondary" : "default"}>
                  <Bot className="mr-2 h-4 w-4" />
                  {showChat ? "Hide Assistant" : "Open AI Assistant"}
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>{showChat ? "Close the AI chat panel" : "Open a conversational AI that can generate messages, explain features, and answer questions about your account."}</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>

        {showChat && (
          <Card>
            <CardContent className="p-0">
              <RebookedAIChat />
            </CardContent>
          </Card>
        )}

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {AI_CAPABILITIES.map((cap) => (
            <Card key={cap.title} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-3">
                <div className="flex items-center gap-3">
                  <cap.icon className={`h-5 w-5 ${cap.color}`} />
                  <HelpTooltip content={cap.tooltip} variant="tip">
                    <CardTitle className="text-base">{cap.title}</CardTitle>
                  </HelpTooltip>
                </div>
              </CardHeader>
              <CardContent>
                <CardDescription>{cap.description}</CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
}
