export const automationTemplates = [
  {
    key: "appointment_confirmation_chase",
    name: "Confirmation Chase",
    category: "appointment",
    trigger: "appointment.booked",
    steps: [{ type: "sms", message: "Hi {{name}}, just checking that you're still good for {{date}} at {{time}}. Reply CONFIRM or RESCHEDULE." }],
  },
  {
    key: "inbound_response_sla",
    name: "Inbound Auto-Reply",
    category: "follow_up",
    trigger: "message.received",
    steps: [{ type: "sms", message: "Thanks for reaching out to {{business}}. We got your message and will text you back shortly." }],
  },
  {
    key: "qualified_followup_1d",
    name: "Qualified Lead Follow-Up (1 Day)",
    category: "follow_up",
    trigger: "lead.created",
    steps: [{ type: "sms", message: "Hi {{name}}, just checking in from {{business}}. Want me to help you grab a time?" }],
  },
  {
    key: "qualified_followup_3d",
    name: "Qualified Lead Follow-Up (3 Days)",
    category: "follow_up",
    trigger: "lead.created",
    steps: [{ type: "sms", message: "Still interested in booking with {{business}}? Reply YES and we'll help you lock in a spot." }],
  },
  {
    key: "delivery_failure_retry",
    name: "Delivery Failure Recovery",
    category: "follow_up",
    trigger: "message.sent",
    steps: [{ type: "sms", message: "We had trouble reaching you earlier. If you still want to book with {{business}}, reply here and we'll help." }],
  },
  {
    key: "next_visit_prompt",
    name: "Next Visit Prompt",
    category: "follow_up",
    trigger: "appointment.booked",
    steps: [{ type: "sms", message: "Thanks again for visiting {{business}}. Want to get your next appointment on the calendar now?" }],
  },
  {
    key: "waitlist_fill",
    name: "Waitlist Fill",
    category: "cancellation",
    trigger: "appointment.cancelled",
    steps: [{ type: "sms", message: "An appointment opening just came up at {{business}}. Want it? Reply YES and we'll hold it for you." }],
  },
  {
    key: "cancellation_same_day",
    name: "Same-Day Cancellation Rescue",
    category: "cancellation",
    trigger: "appointment.cancelled",
    steps: [{ type: "sms", message: "Sorry we missed you today. Want help finding a new time? Reply REBOOK and we'll make it easy." }],
  },
  {
    key: "cancellation_rebooking_48h",
    name: "Cancellation Rescue (48h)",
    category: "cancellation",
    trigger: "appointment.cancelled",
    steps: [{ type: "sms", message: "We still have a few spots open this week if you'd like to rebook. Reply YES and we'll send options." }],
  },
  {
    key: "cancellation_rebooking_7d",
    name: "Cancellation Rescue (7d)",
    category: "cancellation",
    trigger: "appointment.cancelled",
    steps: [{ type: "sms", message: "Last check-in from {{business}}. We'd still love to get you back on the calendar whenever you're ready." }],
  },
  {
    key: "vip_winback_45d",
    name: "VIP Win-Back (45d)",
    category: "reactivation",
    trigger: "appointment.booked",
    steps: [{ type: "sms", message: "Hi {{name}}, we've missed you at {{business}}. Want priority booking for your next visit? Reply VIP." }],
  },
  {
    key: "vip_winback_90d",
    name: "VIP Win-Back (90d)",
    category: "reactivation",
    trigger: "appointment.booked",
    steps: [{ type: "sms", message: "We've saved a special comeback offer for you at {{business}}. Reply YES if you want first pick of availability." }],
  },
  {
    key: "reduce_no_shows",
    name: "Reduce No-Shows",
    category: "no_show",
    trigger: "appointment.no_show",
    steps: [
      { type: "delay", value: 600 },
      { type: "sms", message: "Hey {{first_name}}, we missed you today. Want to reschedule?" },
    ],
  },
  {
    key: "welcome_new_lead",
    name: "Welcome New Lead",
    category: "welcome",
    trigger: "lead.created",
    steps: [
      { type: "sms", message: "Hi {{name}}, thanks for reaching out! Reply with a time that works and we'll book you." },
    ],
  },
  {
    key: "appointment_reminder_24h",
    name: "24-Hour Appointment Reminder",
    category: "appointment",
    trigger: "appointment.reminder_24h",
    steps: [
      { type: "sms", message: "Hi {{name}}, reminder: your appointment at {{business}} is tomorrow at {{time}}. Reply CONFIRM to keep it or RESCHEDULE to change." },
    ],
  },
  {
    key: "appointment_reminder_2h",
    name: "2-Hour Appointment Reminder",
    category: "appointment",
    trigger: "appointment.reminder_2h",
    steps: [
      { type: "sms", message: "Hi {{name}}, just a heads up — your appointment at {{business}} is in 2 hours at {{time}}. See you soon!" },
    ],
  },
  {
    key: "booking_confirmation",
    name: "Booking Confirmation",
    category: "appointment",
    trigger: "appointment.booked",
    steps: [
      { type: "sms", message: "You're all set! Your appointment at {{business}} is confirmed for {{date}} at {{time}}. Reply CANCEL if you need to change plans." },
    ],
  },
  {
    key: "review_request",
    name: "Review Request",
    category: "review",
    trigger: "appointment.completed",
    steps: [
      { type: "delay", value: 3600 },
      { type: "sms", message: "Thanks for visiting {{business}}! We'd love your feedback. Leave us a quick review here: {{review_link}}" },
    ],
  },
  {
    key: "birthday_promo",
    name: "Birthday Promo",
    category: "loyalty",
    trigger: "contact.birthday",
    steps: [
      { type: "sms", message: "Happy birthday, {{name}}! 🎂 {{business}} wants to celebrate with you — enjoy {{discount}} off your next visit. Book now!" },
    ],
  },
  {
    key: "loyalty_milestone",
    name: "Loyalty Milestone",
    category: "loyalty",
    trigger: "contact.milestone",
    steps: [
      { type: "sms", message: "Congrats {{name}}! You've hit {{milestone}} visits at {{business}}. As a thank you, here's a special reward: {{reward}}. Book your next visit!" },
    ],
  },
  {
    key: "post_visit_feedback",
    name: "Post-Visit Feedback",
    category: "follow_up",
    trigger: "appointment.completed",
    steps: [
      { type: "delay", value: 7200 },
      { type: "sms", message: "Hi {{name}}, how was your visit to {{business}} today? Reply 1-5 (5 = amazing). We'd love to hear from you!" },
    ],
  },
  {
    key: "post_visit_upsell",
    name: "Post-Visit Upsell",
    category: "follow_up",
    trigger: "appointment.completed",
    steps: [
      { type: "delay", value: 86400 },
      { type: "sms", message: "Hi {{name}}, loved having you at {{business}}! Did you know we also offer {{upsell_service}}? Reply INFO to learn more." },
    ],
  },
  {
    key: "cancellation_flurry",
    name: "Cancellation Flurry (Waiting List)",
    category: "cancellation",
    trigger: "appointment.cancelled",
    steps: [
      { type: "sms", message: "Great news! A spot just opened up at {{business}} on {{date}} at {{time}}. You're on the waiting list — reply BOOK to grab it before it's gone!" },
    ],
  },
];
